<?php

namespace App\Services;

use Illuminate\Support\Facades\Log;
use ZipArchive;

/**
 * ProjectPackager
 *
 * Responsible for everything related to packaging extracted code:
 * - Generating ZIP archives
 * - Writing READMEs
 * - Adding file headers
 * - Bundling dependency manifests
 */
class ProjectPackager
{
    /** Comment-style templates per language */
    private array $commentStyles = [
        'javascript' => "/**\n * %s\n * Extracted from YouTube tutorial by YouExtractor\n */\n\n",
        'typescript' => "/**\n * %s\n * Extracted from YouTube tutorial by YouExtractor\n */\n\n",
        'python'     => "\"\"\"\n%s\nExtracted from YouTube tutorial by YouExtractor\n\"\"\"\n\n",
        'php'        => "<?php\n/**\n * %s\n * Extracted from YouTube tutorial by YouExtractor\n */\n\n",
        'html'       => "<!-- %s - Extracted from YouTube tutorial by YouExtractor -->\n\n",
        'css'        => "/* %s - Extracted from YouTube tutorial by YouExtractor */\n\n",
        'java'       => "/**\n * %s\n * Extracted from YouTube tutorial by YouExtractor\n */\n\n",
    ];

    /**
     * Build the ZIP archive and return its absolute path, or null on failure.
     */
    public function generateZip(string $videoId, array $codeData): ?string
    {
        $zipPath = storage_path("app/downloads/{$videoId}.zip");
        $zipDir  = dirname($zipPath);

        if (!is_dir($zipDir)) {
            mkdir($zipDir, 0755, true);
        }

        $zip = new ZipArchive();
        if ($zip->open($zipPath, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== true) {
            Log::error("ProjectPackager: Cannot open ZIP at {$zipPath}");
            return null;
        }

        // README
        $zip->addFromString('README.md', $this->buildReadme($codeData));

        // Source files
        foreach ($codeData['files'] ?? [] as $file) {
            $path   = $file['path'] ?? $file['filename'];
            $code   = $file['code'] ?? '';
            $header = $this->buildFileHeader($file);
            $zip->addFromString($path, $header . $code);
        }

        // Setup notes
        if (!empty($codeData['setup_instructions'])) {
            $zip->addFromString(
                'SETUP.md',
                "# Setup Instructions\n\n```bash\n{$codeData['setup_instructions']}\n```"
            );
        }

        // Dependency manifests
        $this->addDependencyManifests($zip, $codeData['dependencies'] ?? []);

        $zip->close();

        return $zipPath;
    }

    // ------------------------------------------------------------------
    // Private helpers
    // ------------------------------------------------------------------

    private function buildReadme(array $codeData): string
    {
        $stack = $codeData['stack'] ?? null;
        $files = $codeData['files'] ?? [];

        $md  = "# Code Extracted from YouTube Video\n\n";
        $md .= "> Generated by **YouExtractor** — Turn YouTube tutorials into runnable code.\n\n";

        if ($stack) {
            $md .= "## Tech Stack\n\n";
            $md .= "| | |\n|---|---|\n";
            $md .= "| **Primary** | {$stack['primary']} |\n";
            if (!empty($stack['languages'])) {
                $md .= '| **Languages** | ' . implode(', ', $stack['languages']) . " |\n";
            }
            if (!empty($stack['frameworks'])) {
                $md .= '| **Frameworks** | ' . implode(', ', $stack['frameworks']) . " |\n";
            }
            if (!empty($stack['description'])) {
                $md .= "\n{$stack['description']}\n";
            }
            $md .= "\n";
        }

        if (!empty($files)) {
            $md .= "## Files (" . count($files) . ")\n\n";
            foreach ($files as $file) {
                $path = $file['path'] ?? $file['filename'];
                $desc = $file['description'] ?? '';
                $md  .= "### `{$path}`\n{$desc}\n\n";
            }
        }

        if (!empty($codeData['setup_instructions'])) {
            $md .= "## Quick Start\n\n";
            $md .= "```bash\n{$codeData['setup_instructions']}\n```\n\n";
        }

        $md .= "---\n*Extracted on: " . date('Y-m-d H:i:s') . "*\n";

        return $md;
    }

    private function buildFileHeader(array $file): string
    {
        $lang = strtolower($file['language'] ?? 'text');
        $desc = $file['description'] ?? '';

        if (isset($this->commentStyles[$lang])) {
            return sprintf($this->commentStyles[$lang], $desc);
        }

        return "// {$desc}\n// Extracted from YouTube tutorial by YouExtractor\n\n";
    }

    private function addDependencyManifests(ZipArchive $zip, array $dependencies): void
    {
        if (!empty($dependencies['npm'])) {
            $pkg = json_encode([
                'name'         => 'youtube-extracted-code',
                'version'      => '1.0.0',
                'dependencies' => array_fill_keys($dependencies['npm'], '*'),
            ], JSON_PRETTY_PRINT);
            $zip->addFromString('package.json', $pkg);
        }

        if (!empty($dependencies['pip'])) {
            $zip->addFromString('requirements.txt', implode("\n", $dependencies['pip']));
        }

        if (!empty($dependencies['composer'])) {
            $pkg = json_encode([
                'name'    => 'youtube/extracted-code',
                'require' => array_fill_keys($dependencies['composer'], '*'),
            ], JSON_PRETTY_PRINT);
            $zip->addFromString('composer.json', $pkg);
        }

        if (!empty($dependencies['maven'])) {
            // Provide a minimal pom.xml stub
            $deps = '';
            foreach ($dependencies['maven'] as $artifact) {
                $parts  = explode(':', $artifact);
                $group  = $parts[0] ?? 'unknown';
                $art    = $parts[1] ?? $artifact;
                $deps  .= "        <dependency>\n"
                        . "            <groupId>{$group}</groupId>\n"
                        . "            <artifactId>{$art}</artifactId>\n"
                        . "        </dependency>\n";
            }
            $pom = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<project>\n    <modelVersion>4.0.0</modelVersion>\n    <groupId>com.example</groupId>\n    <artifactId>youtube-extracted</artifactId>\n    <version>1.0.0</version>\n    <dependencies>\n{$deps}    </dependencies>\n</project>\n";
            $zip->addFromString('pom.xml', $pom);
        }
    }
}
