<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @include('partials.favicon')
    <link rel="canonical" href="{{ rtrim(config('app.url'), '/') . '/' . ltrim(request()->getPathInfo(), '/') }}">
    <script async src="https://aromatic-caribou-889.convex.site/api/a/am_qYeSPvXGoob8W5b-"></script>
    <title>Privacy Policy • YouExtractor - AI YouTube Code Extractor</title>
    <meta name="description" content="YouExtractor's privacy policy. Learn how we handle your data when you extract code projects from YouTube tutorials using our AI tool.">
    
    <!-- Design System CSS -->
    <link rel="stylesheet" href="/css/youextractor-design-system.css?v=5">
    
    <!-- Fonts & Icons -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/@phosphor-icons/web@2.1.1/src/regular/style.css">

    <style>
        body { 
            font-family: var(--theme-font-sans); 
            background: var(--ds-surface-base);
            color: var(--ds-text-primary);
            margin: 0;
            padding: 0;
            min-height: 100vh;
            display: flex;
            flex-direction: column;
            align-items: center;
            box-sizing: border-box;
            /* Verified light theme baseline */
            transition: background-color var(--theme-motion-normal) var(--theme-ease-default), color var(--theme-motion-normal) var(--theme-ease-default);
        }

        .container {
            width: 100%;
            max-width: 800px;
            padding: var(--theme-spacing-8) var(--theme-spacing-6);
            box-sizing: border-box;
            display: flex;
            flex-direction: column;
            gap: var(--theme-spacing-6);
        }

        .header-section {
            display: flex;
            align-items: center;
            justify-content: space-between;
            border-bottom: 1px solid var(--ds-border-subtle);
            padding-bottom: var(--theme-spacing-4);
        }

        .logo {
            display: inline-flex;
            align-items: center;
            gap: var(--theme-spacing-3);
            text-decoration: none;
            color: var(--ds-text-primary);
        }

        .doc-content h1, .doc-content h2, .doc-content h3 {
            color: var(--ds-text-primary);
            margin-top: var(--theme-spacing-6);
        }

        .doc-content p, .doc-content li {
            color: var(--ds-text-secondary);
            line-height: 1.6;
        }

        .doc-content ul {
            padding-left: var(--theme-spacing-5);
        }

        .doc-content li {
            margin-bottom: var(--theme-spacing-2);
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header-section">
            <a href="{{ route('landing') }}" class="logo">
                <img src="/img/youextractor-logo.jpg" alt="YouExtractor" style="width:28px;height:28px;border-radius:5px;object-fit:cover;border:1px solid rgba(20,184,166,0.25);">
                <span class="ds-type-heading-sm" style="margin: 0; font-size: 1.25rem;">YouExtractor</span>
            </a>
            <a href="{{ url()->previous() ?: route('landing') }}" style="text-decoration: none;">
                <ds-button label="Back" variant="glow" size="sm" ></ds-button>
            </a>
        </div>

        <ds-card variant="glass" padding="xl" style="margin-top: 6vh;">
            <div class="doc-content">
                <h1 class="ds-type-heading-md" style="margin-top: 0;">Privacy Policy</h1>
                <p><strong>Last updated: June 4, 2026</strong></p>
                <p>YouExtractor ("we", "our", or "us") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, and disclose your personal information when you use our service.</p>

                <h2 class="ds-type-heading-sm">1. Information We Collect</h2>
                <ul>
                    <li><strong>Account Information:</strong> When you log in via Google or GitHub OAuth, we receive your public profile information (such as your name, email address, and avatar URL).</li>
                    <li><strong>Service Usage:</strong> We collect the YouTube URLs you submit and the code snippets generated by our service.</li>
                    <li><strong>GitHub Access:</strong> If you choose to push code directly to your GitHub account, we collect and use your GitHub Personal Access Token solely to authenticate the API request to create the repository and push the code on your behalf. We do not store this token on our servers.</li>
                </ul>

                <h2 class="ds-type-heading-sm">2. How We Use Your Information</h2>
                <ul>
                    <li>To provide, operate, and maintain the YouExtractor service.</li>
                    <li>To authenticate you and secure your account.</li>
                    <li>To interact with third-party APIs (Google, GitHub, OpenAI, Gemini, Anthropic) to extract and push code.</li>
                </ul>

                <h2 class="ds-type-heading-sm">3. Data Sharing</h2>
                <p>We do not sell or share your personal data with third parties, except as required to interact with the external APIs mentioned above to perform the code extraction and push requests.</p>

                <h2 class="ds-type-heading-sm">4. Contact Us</h2>
                <p>If you have any questions about this Privacy Policy, please open an issue in our repository: <a href="https://github.com/onyedika-glitch/youextractor/issues" style="color: var(--ds-text-brand); text-decoration: none;" target="_blank">onyedika-glitch/youextractor</a></p>
            </div>
        </ds-card>
    </div>
    
    @include('partials.footer')

    <!-- Design System Scripts -->
    <script src="/js/youextractor-design-system.js?v=3"></script>
</body>
</html>
